### ISSUE TITLE
[latex] Compilation fails due to font issue when using `itemize` environment

### ISSUE THREAD

**Issue by emvalbuena** [mmngreco/dex#3]
**Description**
Compiling a LaTeX document with an `itemize` environment using the provided Docker image results in a font-related error. However, the document compiles without issues when I use the `enumerate` environment instead.

**Steps to Reproduce**
1. Create a file `mwe.tex` with the following LaTeX code:

```latex
\documentclass{article}

\begin{document}

\section*{Testing Itemize Environment}

This is a test to demonstrate a compilation issue with the `itemize` environment.

\begin{itemize}
  \item First item
  \item Second item
\end{itemize}

\end{document}
```

2. Run the following command to compile the document using the Docker image:

```shell
dexliveonfly mwe.tex
```

**Expected Behavior**
The document should compile to a PDF without any errors.

**Actual Behavior**
The compilation process fails with the following error:

```
!pdfTeX error: pdflatex (file tcrm1200): Font tcrm1200 at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
 ```

**Environment**
- Docker image: `mmngreco/dex:latest`
- Host OS: macOS Sonoma `14.4.1`

**Additional Context**
The same LaTeX file compiles without error when the `itemize` environment is replaced with an `enumerate` environment.

```diff
\documentclass{article}

\begin{document}

\section*{Testing Itemize Environment}

This is a test to demonstrate a compilation issue with the `itemize` environment.

-\begin{itemize}
+\begin{enumerate}
  \item First item
  \item Second item
-\end{itemize}
+\end{enumerate}

\end{document}
```

**Comment by asdf8601** [comment]
Hey @KikeM,

Thank you for opening this issue, i was able to reproduce the error and here are my findings:

- you can use `xelatex` instead of `pdflatex` as a compiler, you have multiple options to achieve this.
   - using compiler option: `dexliveonfly -cxelatex mwe.tex`
   - using xelatex directly: `dex xelatex mwe.tex`


```bash
➜  dex git:(main) ✗ dexliveonfly -cxelatex mwe.tex 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platf
orm was requested
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-08-30>
(/opt/texlive/texdir/texmf-dist/tex/latex/base/article.cls
Document Class: article 2024/02/08 v1.4n Standard LaTeX document class
(/opt/texlive/texdir/texmf-dist/tex/latex/base/size10.clo))
(/opt/texlive/texdir/texmf-dist/tex/latex/l3backend/l3backend-xetex.def)
(./mwe.aux) (/opt/texlive/texdir/texmf-dist/tex/latex/base/ts1cmr.fd)
[1] (./mwe.aux) )
Output written on mwe.pdf (1 page).
SyncTeX written on mwe.synctex.gz.
Transcript written on mwe.log.
```

![image](https://github.com/user-attachments/assets/3e6bc19d-2a11-480d-b5bb-194a4e652e95)

if this solves your issue, please close the issue ;-)
